name = "MicrobeAgents"
uuid = "b17a4bac-8667-4a2d-84f7-1883ae0b8dbb"
authors = ["Riccardo Foffi <rfoffi@ethz.ch> and contributors"]
version = "0.4.1"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
Autocorrelations = "b9118d5e-f165-4cbd-b2ae-b030566b7b26"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LightSumTypes = "f56206fc-af4c-5561-a72a-43fe2ca5a923"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeanSquaredDisplacement = "13c93d70-909c-440c-af92-39d48ffa2ba2"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Agents = "6"
Autocorrelations = "0.1"
DataFrames = "1"
Distributions = "0.25"
GeometryBasics = "0.4"
LightSumTypes = "4"
MeanSquaredDisplacement = "0.2"
Quaternions = "0.7"
StaticArrays = "1"
StatsBase = "0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
