name = "MicrobeAgents"
uuid = "b17a4bac-8667-4a2d-84f7-1883ae0b8dbb"
authors = ["Riccardo Foffi <rfoffi@ethz.ch> and contributors"]
version = "0.2.0"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AxisArrays = "0.4"
CellListMap = "0.8"
DSP = "0.7"
Distributions = "0.25"
GeometryBasics = "0.4"
OffsetArrays = "1"
Rotations = "1"
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
